#!/bin/bash
# aliases and functions

alias la="ls -la"
alias lt="ls -lt" 
alias lta="ls -lta"
alias ltd="ls -ltd"

alias ..="cd ../"                   
alias ...="cd ../../"               
alias ....="cd ../../../"           
alias .....="cd ../../../../"           

alias vi="vim"


# Conda
alias mfa="source ~/Programs/miniforge3/etc/profile.d/conda.sh; conda activate"
alias mfd="conda deactivate"
alias mf="conda"

# lobos 
alias jblobos="export LOBOS_JNB_PORT_NUM=8989; ssh -L localhost:\${LOBOS_JNB_PORT_NUM}}:localhost:\${LOBOS_JNB_PORT_NUM} lobos"
alias scplobos="scp -rpq -P 1701"
alias rsynclobos="rsync -a -e -v \'ssh -p 1701\'"


alias ub="nohup /Applications/Übersicht.app/Contents/MacOS/Übersicht &"
