#!/bin/bash
# Bash login shells start by reading:
# Settings here are for important, one-time things when Bash starts up.

export BASH_SILENCE_DEPRECATION_WARNING=1

if [ -f ${HOME}/.bashrc ]; then 
    source ${HOME}/.bashrc
fi

# Causes bash to append to history instead of overwriting it so if you start a new terminal, you have old session history
shopt -s histappend
PROMPT_COMMAND='history -a'

# Homembrew Programs
eval "$(/opt/homebrew/bin/brew shellenv)"
export PATH="$(brew --prefix)/opt/gnu-sed/libexec/gnubin:${PATH}" # GNU `sed`

if [ -f $(brew --prefix)/etc/profile.d/autojump.sh ]; then
    source $(brew --prefix)/etc/profile.d/autojump.sh
fi
