#!/bin/bash

PARTITION="batch"
NODES=1
NTASK=32
MEM="20G"
TIME="12:00:00"
JOBNAME="int"

# Check if the partition exists
if ! command -v sinfo >/dev/null 2>&1; then
    echo "missing: sinfo"
    exit
elif ! sinfo -h -o "%P" | awk -F'[*]' '{print $1}' | grep -qw "$PARTITION"; then
    echo "Error: Partition '$PARTITION' does not exist."
    echo "Available partitions are:"
    sinfo -h -o "%P" | awk -F'[*]' '{print $1}' | sort -u
    exit 1
fi

srun --pty -p ${PARTITION} -N ${NODES} -n ${NTASK} --mem=$MEM -t ${TIME} -J ${JOBNAME} /bin/bash

