#!/scratch/van/shared_envs/ambertools23/bin/python
import sys
from glob import glob
import numpy as np
import pytraj as pt

from organize import parse_input, mkdir, count_name
from to-pandas import matrix2dataframe
from to-pytraj import calc_rmsd2d
from quickplot import quickmatplot

def main():
    args = parse_input()
    trajectory = sorted(glob(f'{args.nc}*.nc'))
    parm = f'{args.parm}.parm7'

    traj = pt.iterload(trajectory, top=parm)
    data = calc_rmsd2d(traj, mask=f'{args.mask}')
    
    results = matrix2dataframe(data)

    xlabel="Frame Number"
    ylabel="Frame Number"
    mkdir('img')
    name = count_name('rmsd2d')
    quickmatplot(data, xlabel, ylabel, name)


if __name__ == '__main__':
    main()
