#!/scratch/van/shared_envs/ambertools23/bin/python
import sys
import argparse
import subprocess

analysis = ['all', 'rmsd', 'rmsd2d', 'rmsf', 'pca']

def parse_inputs():
    parser=argparse.ArgumentParser(description="a script to do stuff")
    parser.add_argument('-r', '--run', choices=analysis)
    args=parser.parse_args()
    return args

def run(analysis):
    cmd=[f'/projects/ok001/van/p/{analysis}']
    subprocess.run(cmd)


def main():
    args = parse_inputs()
    if args.run == 'all':
        print(f"Running: {analysis}")
        for ana in analysis[1:]:
            run(ana)
    else:
        print(f"Running: {args.run}")
        run(args.run)
    

if __name__ == '__main__':
    main()
