#!/usr/bin/python3
import os
import sys
from glob import glob
import argparse
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument('step', type=str, default='5',
        help='filename for step...')
parser.add_argument('index', choices=['0', '1','2','3','4','5', 'all'], default='all',
        help='index of step (step5.00')
args = parser.parse_args()


dirnames = sorted(glob(f'{os.getcwd()}/??'))
n_windows = len(dirnames)


print(f'n_W\tn_CVs')

for n in range(n_windows):
    if os.path.isdir(f'{n:02d}') is True:
        if args.index != 'all':
            filename = f'step{args.step}.0{args.index}_equilibration.cv'
        else:
            sys.quit()

        if os.path.isfile(f'{n:02d}/{filename}') is True:
            with open(f'{n:02d}/{filename}', 'r') as f:
                len_f = len(f.readlines())
            print(f'{n:02d}\t{len_f}')
        else:
            print(f'{n:02d}\t0')

    else:
        print('Missing dir')
    

