#!/scratch/van/shared_envs/ambertools23/bin/python
import sys
from glob import glob
import numpy as np
import pytraj as pt

from organize import parse_input, mkdir, count_name
from to-pandas import matrix2dataframe
from to-pytraj import calc_rmsf
from quickplot import quickplot


def get_resnum(data):
    max_residues = len(data) + 1
    return np.arange(1, max_residues)

def plot_rmsf(data):
    xdat = get_resnum(data.T[0])
    ydat = data.T[1]

    xlab="Residue Number"
    ylab="RMSF (Å)"
    mkdir('img')
    name = count_name('rmsf')
    quickplot(xdat, ydat, xlab, ylab, name)

def main():
    args = parse_input()
    trajectory = sorted(glob(f'{args.nc}*.nc'))
    parm = f'{args.parm}.parm7'

    traj = pt.iterload(trajectory, top=parm)
    data = calc_rmsf(traj, mask=f'{args.mask}')
    
    results = matrix2dataframe(data)


if __name__ == '__main__':
    main()
