#!/bin/bash
# Check if file exists
# INP can be file in current directory or path to file
# 

INP=${1}

if [ -e "${INP}" ]; then
    echo "Found: ${INP} !!!"
else
    echo "Missing: ${INP} "
    exit 1
fi
