#!/bin/bash

if [ -z "${1}" ]; then
    APP="app.def"
    echo "Assume apptainer definition file name: ${APP}.def"
else
    if [ $(echo ${1} | tr '.' '\t' | wc -w) -ge 2 ]; then
        APP=$(echo $1 | awk -F '.' '{print $1}')
    else
        APP="${1}"
    fi
    echo "Using apptainer definition file name: ${APP}.def"
fi

if [ -z "${2}" ]; then
    echo "Need sandbox dirname"
    exit 0
fi

apptainer build --sandbox /tmp/${2} ${APP}
