#!/bin/bash

if [ -z "${1}" ]; then
    APP="app"
    echo "Assume apptainer definition file name: ${APP}.sif"
else
    if [ $(echo ${1} | tr '.' '\t' | wc -w) -ge 2 ]; then
        APP=$(echo $1 | awk -F '.' '{print $1}')
    else
        APP="${1}"
    fi
    echo "Using apptainer definition file name: ${APP}.sif"
fi

input=$1
apptainer shell -Ccw $input
