" vim config with tmux and autocomplete

" line numbers
set number

" syntax highlight
syntax on

" ignore case in search
set ignorecase
set smartcase
set incsearch
set lazyredraw
set magic
set showmatch
set mat=2

" Disable highlight when <leader><cr> is pressed
" "map <silent> <leader><cr> :noh<cr>
set nohlsearch

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""" file management       


" text/tab/index
set expandtab           " use spaces
set shiftwidth=4        " 1 tab = 4 spaces
set tabstop=4
set softtabstop=4       " 
set lbr
set tw=500              " line break @ 500 characters
set ai " auto indent 
set si " smart indent
set wrap " wrap lines

" filetype plugins
filetype plugin indent on

" correct backspace
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

" auto update
set autoread
au FocusGained, BufEnter * silent? checktime

" spell check
map <leader>ss :setlocal spell!<cr>

" files/backup
set noswapfile
" set nobackup
set nowb

"" auto close 
"inoremap " ""<left>
"inoremap ' ''<left>
"inoremap ( ()<left>
"inoremap [ []<left>
"inoremap { {}<left>
"inoremap {<CR> {<CR>}<ESC>O
"inoremap {;<CR> {<CR>};<ESC>O

" turn off sound
set noerrorbells
set novisualbell
set t_vb=
set tm=500
if has("gui_macvim")
        autocmd GUIEnter * set vb t_vb
endif


"""""""""""""""""""""""""""""""
" vim autocomplete 
" https://github.com/neoclide/coc.nvim
"
" 1. install vim>9.0 
"
" sudo add-apt-repository ppa:jonathonf/vim
" sudo apt update
" sudo apt install vim
"
" 2. install nodejs>16 (with homebrew
"
" brew install node@20
" node -v
" npm -v
" 
" 
" To install/update, start vim  and run :PlugInstall or :PlugUpdate
call plug#begin()
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

" Use tab for trigger completion with characters ahead and navigate
" NOTE: There's always complete item selected by default, you may want to enable
" no select by `"suggest.noselect": true` in your configuration file
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1) :
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

" Make <CR> to accept selected completion item or notify coc.nvim to format
" <C-g>u breaks current undo, please make your own choice
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"


"tab autocompletion mapping (:CocInstall coc-snippets, coc-json)
"inoremap <silent><expr> <TAB>
"            \ coc#pum#visible() ? coc#_select_confirm() :
"            \ coc#expandableOrJumpable() ?
"            \ CheckBackspace() ? "\<TAB>" :
"            \ coc#refresh()

function! CheckBackspace() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~# '\s'
endfunction

let g:coc_snippet_next = '<tab>'

" tmux
let g:tmux_navigator_no_mappings = 1

noremap <silent> {Left-Mapping} :<C-U>TmuxNavigateLeft<cr>
noremap <silent> {Down-Mapping} :<C-U>TmuxNavigateDown<cr>
noremap <silent> {Up-Mapping} :<C-U>TmuxNavigateUp<cr>
noremap <silent> {Right-Mapping} :<C-U>TmuxNavigateRight<cr>
noremap <silent> {Previous-Mapping} :<C-U>TmuxNavigatePrevious<cr>
