#!/bin/bash


export APP_PATH="/home/van/apptainer/apps"

function vmdapp () {
    #apptainer exec /archive/van/apptainer/apps/vmd-1.9.4.a57.sif "$@"
    $APP_PATH/vmd.sif
}

function webdevapp () {
    apptainer exec /archive/van/apptainer/apps/miniforge3/webdev.sif "$@"
}

