#!/bin/bash
# MINICONDA
#
function mfa () {
    if [ -d "${HOME}/Programs/miniforge3" ]; then
        source ${HOME}/Programs/miniforge3/etc/profile.d/conda.sh
    elif [ -d /opt/conda ]; then
        source /opt/conda/etc/profile.d/conda.sh
    fi
    conda info
    conda activate "$@"
}



